[package]
name = "tah-web"
version = "0.1.0"
authors = ["Saren Currie <saren@sarencurrie.com>"]

[dependencies]
rouille = "2.1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rusqlite = "0.13.0"
